[tox]
envlist =
    py{312,313,314}-django{52,60}
    ruff
    docs
skip_missing_interpreters = true

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
DJANGO =
    5.2: django52
    6.0: django60

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE=tests.settings_pg
    PYTHONPATH={toxinidir}
passenv =
    PGHOST
    PGPORT
    PGUSER
    PGPASSWORD
extras =
    tests
deps =
  django52: Django~=5.2.0
  django60: Django~=6.0.0
commands =
  pytest tests \
   --cov --cov-report xml:reports/coverage-{envname}.xml \
   {posargs}

[testenv:ruff]
extras = tests
skipsdist = True
commands_pre =
commands =
    ruff check --output-format=github .
    ruff format --check

[testenv:docs]
basepython=python
changedir=docs
skipsdist=true
extras =
    tests
    docs
allowlist_externals = make
commands_pre =
commands=
    make SPHINXOPTS="-W" html
    make linkcheck
