# Generated by Django 3.2.12 on 2022-04-13 07:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline_logger", "0004_alter_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinelog",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="extra data",
            ),
        ),
        migrations.AlterField(
            model_name="timelinelog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
