# Generated by Django 3.2.12 on 2022-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline_logger", "0005_auto_20220413_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinelog",
            name="object_id",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="object id"
            ),
        ),
        migrations.AlterField(
            model_name="timelinelog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="timestamp"
            ),
        ),
    ]
