# Generated by Django 4.2.28 on 2026-02-09 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline_logger", "0006_auto_20220413_0749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinelog",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="timestamp",
            ),
        ),
    ]
