name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: "23 5 * * *"
  workflow_dispatch:

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [isort, black, flake8, docs]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: pip install tox
      - run: tox --colored=yes
        env:
          TOXENV: ${{ matrix.toxenv }}
          FORCE_COLOR: '1'
